### PR TITLE
Add simple NUnit assertions for booleans and Null

### PR DESCRIPTION
**Pull request by mu88**
@inyutin-maxim Thank you for your amazing job! Due to your fundamentals, adding these simple assertions was super easy 👏🏻

### CODE REVIEW

**Comment by inyutin-maxim** [comment]
I think be cool add a test cases. You can add to folder `/src/dotnet/ReSharperPlugin.FluentAssertions.Tests/test/data/NUnitAssertMigrationQuickFixTests/`
files:
- PositiveCaseFalse.cs - file contains case for replace a code. You can see [example](https://github.com/matkoch/resharper-fluentassertions/blob/master/src/dotnet/ReSharperPlugin.FluentAssertions.Tests/test/data/NUnitAssertMigrationQuickFixTests/PositiveCaseIsNotNull.cs)
- PositiveCaseFalse.cs.gold - file contains result after quickfix. You can see [example](https://github.com/matkoch/resharper-fluentassertions/blob/master/src/dotnet/ReSharperPlugin.FluentAssertions.Tests/test/data/NUnitAssertMigrationQuickFixTests/PositiveCaseIsNotNull.cs.gold)

- PositiveCaseIsFalse.cs - file contains case for replace a code. You can see [example](https://github.com/matkoch/resharper-fluentassertions/blob/master/src/dotnet/ReSharperPlugin.FluentAssertions.Tests/test/data/NUnitAssertMigrationQuickFixTests/PositiveCaseIsNotNull.cs)
- PositiveCaseIsFalse.cs.gold - file contains result after quickfix. You can see [example](https://github.com/matkoch/resharper-fluentassertions/blob/master/src/dotnet/ReSharperPlugin.FluentAssertions.Tests/test/data/NUnitAssertMigrationQuickFixTests/PositiveCaseIsNotNull.cs.gold)

etc

**Comment by mu88** [comment]
Honestly, I didn't really understand your test name pattern, but I hope that's what you're looking for :)

How can I execute the tests? When simply running them in Rider, each and every test fails with `No build requested on commandline`.  
If the tests can be run from the CLI, I'd like to setup a build pipeline as I did it already [here](https://github.com/vladyslav-burylov/resharper-testlinker2/blob/master/.github/workflows/CI.yml)

**Comment by inyutin-maxim** [comment]
> Honestly, I didn't really understand your test name pattern, but I hope that's what you're looking for :)
> 
> How can I execute the tests? When simply running them in Rider, each and every test fails with `No build requested on commandline`. If the tests can be run from the CLI, I'd like to setup a build pipeline as I did it already [here](https://github.com/vladyslav-burylov/resharper-testlinker2/blob/master/.github/workflows/CI.yml)

You got the test naming pattern right. I have all tests running correctly on Windows 11. Under Kubuntu 21.10, I could not run the tests they also fall. I think I misconfigured the environment, maybe we could help with this @matkoch

**Comment by mu88** [comment]
And did you have to install/configure something to run the tests or can you simply run `dotnet test` on your machine and it works? I have never seen these `gold` files before...

**Comment by inyutin-maxim** [comment]
> And did you have to install/configure something to run the tests or can you simply run `dotnet test` on your machine and it works?

On my Windows station i install only `dotnet core 6 sdk` and all works fine. For linux environment i install `Mono sdk`, `dotnet core 6 sdk` but all tests failed.

>  I have never seen these `gold` files before...

`*.gold` file - this expected result snapshot after quickfix

**Comment by mu88** [comment]
How do you run the tests? Are you calling `dotnet test` from the CLI? Or are you starting them from Visual Studio? Or are you using Rider?

**Comment by mu88** [comment]
Ah, I forgot to update `Plugin.props`, now it looks "better" - I'm getting a NuGet restore error, but that's probably because of the corporate proxy I'm behind - at least four tests are running now, I'll try the others later at home.

@inyutin-maxim is the code base in this PR fine for you so that @matkoch could do the merge?

**Comment by inyutin-maxim** [comment]
> @inyutin-maxim is the code base in this PR fine for you so that @matkoch could do the merge?

Yes, of course, it looks good to me

**Pull request merged**
